template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "norw1259"
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokmål"
__UND__ = "nob"
