template = "https://github.com/giellalt/template-lang-und"
rev_id = 338
template_sha = "f8f3c0370220064ccae6868bc90707e0583f91c2"

[replacements]
__GLOTTOLOG_ID__ = "norw1259"
__REPO__ = "lang-nob"
__UND2C__ = "nb"
__UNDEFINED__ = "Norwegian Bokmål"
__UND__ = "nob"
