[package]
name = "nob"
human_name = "Norwegian Bokmål"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.nob]
filename = "nb-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-nob"
platform = "windows"
uuid = "0BEB7B50-5408-48BE-9AED-18992977BD6B"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.nb"
package = "speller-nob"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-nob-mso"
platform = "windows"
uuid = "E5B12E99-8DD0-4D7B-9B1D-913CB04728A1"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-nob"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
